server:
  port: 8080

spring:
  datasource:
    username: root
    password: ----
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&serverTimezone=UTC&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

indexing-settings:
   sites:
     - url: https://www.playback.ru
       name: PlayBack.ru
#     - url: https://dimonvideo.ru
#       name: DimonVideo.ru
     - url: http://radiomv.ru
       name: RadioMV.ru

connection-settings:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com